export interface CurrencyOption {
  name: string;
  code: string;
  symbol: string;
}

export const currencies: CurrencyOption[] = [
  { name: "US Dollar", code: "USD", symbol: "$" },
  { name: "Euro", code: "EUR", symbol: "€" },
  { name: "British Pound", code: "GBP", symbol: "£" },
  { name: "Indian Rupee", code: "INR", symbol: "₹" },
  { name: "Australian Dollar", code: "AUD", symbol: "A$" },
  { name: "Canadian Dollar", code: "CAD", symbol: "C$" },
  { name: "Swiss Franc", code: "CHF", symbol: "CHF" },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
  { name: "Japanese Yen", code: "JPY", symbol: "¥" },
  { name: "New Zealand Dollar", code: "NZD", symbol: "NZ$" },
  { name: "United Arab Emirates Dirham", code: "AED", symbol: "د.إ" },
  { name: "Argentine Peso", code: "ARS", symbol: "$" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$" },
  { name: "Chilean Peso", code: "CLP", symbol: "$" },
  { name: "Colombian Peso", code: "COP", symbol: "$" },
  { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
  { name: "Danish Krone", code: "DKK", symbol: "kr" },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "HK$" },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
  { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  { name: "Mexican Peso", code: "MXN", symbol: "$" },
  { name: "Nigerian Naira", code: "NGN", symbol: "₦" },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
  { name: "Philippine Peso", code: "PHP", symbol: "₱" },
  { name: "Polish Zloty", code: "PLN", symbol: "zł" },
  { name: "Russian Ruble", code: "RUB", symbol: "₽" },
  { name: "Saudi Riyal", code: "SAR", symbol: "SR" },
  { name: "Singapore Dollar", code: "SGD", symbol: "S$" },
  { name: "South African Rand", code: "ZAR", symbol: "R" },
  { name: "South Korean Won", code: "KRW", symbol: "₩" },
  { name: "Swedish Krona", code: "SEK", symbol: "kr" },
  { name: "Taiwan New Dollar", code: "TWD", symbol: "NT$" },
  { name: "Thai Baht", code: "THB", symbol: "฿" },
  { name: "Turkish Lira", code: "TRY", symbol: "₺" },
  { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
  { name: "Vietnamese Dong", code: "VND", symbol: "₫" },
];
